import { Objective, Team, Individual } from './types';
import { TeamDef } from './calendarSettings';

// ─── Default demo objectives ──────────────────────────────────────────────────
// Fictional SaaS company "Nexus" — CY2026
// Mix of annual (Q1–Q4) and quarterly objectives to showcase all views

export const defaultObjectives: Objective[] = [

  // ── Annual objectives ──────────────────────────────────────────────────────

  {
    id: 'obj-eng-1',
    title: 'Platform Scale',
    description: 'Deliver a resilient, scalable platform capable of supporting 10× customer growth',
    owner: 'Alex Rivera',
    teamId: 'engineering',
    quarter: 'Q1',
    quarters: ['Q1', 'Q2', 'Q3', 'Q4'],
    cadence: 'yearly',
    year: 2026,
    startDate: '2026-01-01',
    endDate: '2026-12-31',
    status: 'on-track',
    progress: 58,
    tags: ['infrastructure', 'reliability', 'scalability'],
    keyResults: [
      {
        id: 'kr-eng-1-1',
        title: 'Achieve 99.9% platform uptime across all production services',
        owner: 'Alex Rivera',
        target: 99.9,
        current: 99.7,
        unit: '%',
        dueDate: '2026-12-31',
        status: 'on-track',
        progress: 75,
        lastUpdated: '2026-05-01',
      },
      {
        id: 'kr-eng-1-2',
        title: 'Reduce P95 API response time from 450ms to under 200ms',
        owner: 'Sam Chen',
        target: 200,
        current: 310,
        unit: 'ms',
        dueDate: '2026-12-31',
        status: 'on-track',
        progress: 57,
        lastUpdated: '2026-05-01',
      },
      {
        id: 'kr-eng-1-3',
        title: 'Complete microservices migration for 8 core platform modules',
        owner: 'Priya Nair',
        target: 8,
        current: 3,
        unit: 'modules',
        dueDate: '2026-12-31',
        status: 'on-track',
        progress: 38,
        lastUpdated: '2026-05-01',
      },
    ],
  },

  {
    id: 'obj-sales-1',
    title: 'Revenue Growth',
    description: 'Grow ARR from $12M to $20M through new logo acquisition and account expansion',
    owner: 'Jordan Blake',
    teamId: 'sales',
    quarter: 'Q1',
    quarters: ['Q1', 'Q2', 'Q3', 'Q4'],
    cadence: 'yearly',
    year: 2026,
    startDate: '2026-01-01',
    endDate: '2026-12-31',
    status: 'at-risk',
    progress: 28,
    tags: ['arr', 'new-logos', 'expansion', 'revenue'],
    keyResults: [
      {
        id: 'kr-sales-1-1',
        title: 'Close 40 new enterprise accounts',
        owner: 'Jordan Blake',
        target: 40,
        current: 9,
        unit: 'accounts',
        dueDate: '2026-12-31',
        status: 'at-risk',
        progress: 23,
        lastUpdated: '2026-05-01',
      },
      {
        id: 'kr-sales-1-2',
        title: 'Expand ARR in existing accounts by $3M',
        owner: 'Maya Patel',
        target: 3,
        current: 0.7,
        unit: '$M',
        dueDate: '2026-12-31',
        status: 'at-risk',
        progress: 23,
        lastUpdated: '2026-05-01',
      },
      {
        id: 'kr-sales-1-3',
        title: 'Increase average contract value from $28k to $42k',
        owner: 'Jordan Blake',
        target: 42,
        current: 33,
        unit: '$k',
        dueDate: '2026-12-31',
        status: 'on-track',
        progress: 36,
        lastUpdated: '2026-05-01',
      },
    ],
  },

  {
    id: 'obj-cs-1',
    title: 'Customer Excellence',
    description: 'Achieve best-in-class retention and satisfaction scores across the customer base',
    owner: 'Fatima Al-Sayed',
    teamId: 'customer-success',
    quarter: 'Q1',
    quarters: ['Q1', 'Q2', 'Q3', 'Q4'],
    cadence: 'yearly',
    year: 2026,
    startDate: '2026-01-01',
    endDate: '2026-12-31',
    status: 'on-track',
    progress: 66,
    tags: ['nps', 'churn', 'csat', 'retention'],
    keyResults: [
      {
        id: 'kr-cs-1-1',
        title: 'Achieve NPS of 65 or above (up from 48)',
        owner: 'Fatima Al-Sayed',
        target: 65,
        current: 57,
        unit: 'score',
        dueDate: '2026-12-31',
        status: 'on-track',
        progress: 53,
        lastUpdated: '2026-05-01',
      },
      {
        id: 'kr-cs-1-2',
        title: 'Reduce annual gross churn from 9% to below 5%',
        owner: 'Marcus Lee',
        target: 5,
        current: 6.8,
        unit: '%',
        dueDate: '2026-12-31',
        status: 'on-track',
        progress: 55,
        lastUpdated: '2026-05-01',
      },
      {
        id: 'kr-cs-1-3',
        title: 'Reach 95% CSAT on all support tickets',
        owner: 'Fatima Al-Sayed',
        target: 95,
        current: 91,
        unit: '%',
        dueDate: '2026-12-31',
        status: 'on-track',
        progress: 80,
        lastUpdated: '2026-05-01',
      },
    ],
  },

  {
    id: 'obj-prod-1',
    title: 'Product Leadership',
    description: 'Ship a next-generation product suite that wins competitive enterprise deals',
    owner: 'Chloe Dubois',
    teamId: 'product',
    quarter: 'Q1',
    quarters: ['Q1', 'Q2', 'Q3', 'Q4'],
    cadence: 'yearly',
    year: 2026,
    startDate: '2026-01-01',
    endDate: '2026-12-31',
    status: 'on-track',
    progress: 52,
    tags: ['enterprise', 'features', 'time-to-value'],
    keyResults: [
      {
        id: 'kr-prod-1-1',
        title: 'Launch 4 enterprise-tier features rated P0 by Sales',
        owner: 'Chloe Dubois',
        target: 4,
        current: 2,
        unit: 'features',
        dueDate: '2026-12-31',
        status: 'on-track',
        progress: 50,
        lastUpdated: '2026-05-01',
      },
      {
        id: 'kr-prod-1-2',
        title: 'Reduce time-to-first-value for new customers from 14 days to 5 days',
        owner: 'Daniel Park',
        target: 5,
        current: 8,
        unit: 'days',
        dueDate: '2026-12-31',
        status: 'on-track',
        progress: 67,
        lastUpdated: '2026-05-01',
      },
      {
        id: 'kr-prod-1-3',
        title: 'Achieve 40% weekly active usage rate across enterprise accounts',
        owner: 'Chloe Dubois',
        target: 40,
        current: 27,
        unit: '%',
        dueDate: '2026-12-31',
        status: 'on-track',
        progress: 68,
        lastUpdated: '2026-05-01',
      },
    ],
  },

  {
    id: 'obj-people-1',
    title: 'Talent & Culture',
    description: 'Build the team and culture required to scale the business through 2026 and beyond',
    owner: 'Ingrid Larsson',
    teamId: 'people',
    quarter: 'Q1',
    quarters: ['Q1', 'Q2', 'Q3', 'Q4'],
    cadence: 'yearly',
    year: 2026,
    startDate: '2026-01-01',
    endDate: '2026-12-31',
    status: 'on-track',
    progress: 55,
    tags: ['hiring', 'engagement', 'performance'],
    keyResults: [
      {
        id: 'kr-people-1-1',
        title: 'Hire 24 people across Engineering, Sales, and Customer Success',
        owner: 'Ingrid Larsson',
        target: 24,
        current: 13,
        unit: 'hires',
        dueDate: '2026-12-31',
        status: 'on-track',
        progress: 54,
        lastUpdated: '2026-05-01',
      },
      {
        id: 'kr-people-1-2',
        title: 'Achieve employee engagement score above 7.5 out of 10',
        owner: 'Ingrid Larsson',
        target: 7.5,
        current: 7.2,
        unit: 'score',
        dueDate: '2026-12-31',
        status: 'on-track',
        progress: 72,
        lastUpdated: '2026-05-01',
      },
      {
        id: 'kr-people-1-3',
        title: 'Complete structured career frameworks for all 6 departments',
        owner: 'Tomas Varga',
        target: 6,
        current: 2,
        unit: 'depts',
        dueDate: '2026-12-31',
        status: 'at-risk',
        progress: 33,
        lastUpdated: '2026-05-01',
      },
    ],
  },

  // ── Q1 2026 objectives (completed) ────────────────────────────────────────

  {
    id: 'obj-cs-2',
    title: 'Onboarding Revamp',
    description: 'Redesign the customer onboarding experience to cut time-to-value in half',
    owner: 'Marcus Lee',
    teamId: 'customer-success',
    quarter: 'Q1',
    quarters: ['Q1'],
    cadence: 'quarterly',
    year: 2026,
    startDate: '2026-01-01',
    endDate: '2026-03-31',
    status: 'completed',
    progress: 100,
    tags: ['onboarding', 'time-to-value'],
    keyResults: [
      {
        id: 'kr-cs-2-1',
        title: 'Reduce median onboarding duration from 14 days to 7 days',
        owner: 'Marcus Lee',
        target: 7,
        current: 6,
        unit: 'days',
        dueDate: '2026-03-31',
        status: 'completed',
        progress: 100,
        lastUpdated: '2026-03-31',
      },
      {
        id: 'kr-cs-2-2',
        title: 'Launch self-serve onboarding portal with video walkthroughs',
        owner: 'Fatima Al-Sayed',
        target: 1,
        current: 1,
        unit: 'portal',
        dueDate: '2026-03-31',
        status: 'completed',
        progress: 100,
        lastUpdated: '2026-03-31',
      },
      {
        id: 'kr-cs-2-3',
        title: 'Achieve 85% completion rate on onboarding checklist',
        owner: 'Marcus Lee',
        target: 85,
        current: 91,
        unit: '%',
        dueDate: '2026-03-31',
        status: 'completed',
        progress: 100,
        lastUpdated: '2026-03-31',
      },
    ],
  },

  {
    id: 'obj-mktg-1',
    title: 'Q1 Demand Generation',
    description: 'Build top-of-funnel pipeline and establish Nexus as a category leader in Q1',
    owner: 'Yuki Tanaka',
    teamId: 'marketing',
    quarter: 'Q1',
    quarters: ['Q1'],
    cadence: 'quarterly',
    year: 2026,
    startDate: '2026-01-01',
    endDate: '2026-03-31',
    status: 'completed',
    progress: 94,
    tags: ['pipeline', 'content', 'demand-gen'],
    keyResults: [
      {
        id: 'kr-mktg-1-1',
        title: 'Generate 480 marketing-qualified leads in Q1',
        owner: 'Yuki Tanaka',
        target: 480,
        current: 461,
        unit: 'MQLs',
        dueDate: '2026-03-31',
        status: 'completed',
        progress: 96,
        lastUpdated: '2026-03-31',
      },
      {
        id: 'kr-mktg-1-2',
        title: 'Publish 10 high-quality blog posts and 2 whitepapers',
        owner: 'Remi Okafor',
        target: 12,
        current: 11,
        unit: 'pieces',
        dueDate: '2026-03-31',
        status: 'completed',
        progress: 92,
        lastUpdated: '2026-03-31',
      },
      {
        id: 'kr-mktg-1-3',
        title: 'Achieve 18% increase in organic search traffic vs Q4 2025',
        owner: 'Yuki Tanaka',
        target: 18,
        current: 16,
        unit: '%',
        dueDate: '2026-03-31',
        status: 'completed',
        progress: 89,
        lastUpdated: '2026-03-31',
      },
    ],
  },

  // ── Q2 2026 objectives (in progress) ──────────────────────────────────────

  {
    id: 'obj-eng-2',
    title: 'Security & Compliance',
    description: 'Achieve SOC 2 Type II certification and close all critical security findings',
    owner: 'Sam Chen',
    teamId: 'engineering',
    quarter: 'Q2',
    quarters: ['Q2'],
    cadence: 'quarterly',
    year: 2026,
    startDate: '2026-04-01',
    endDate: '2026-06-30',
    status: 'at-risk',
    progress: 38,
    tags: ['security', 'soc2', 'compliance'],
    keyResults: [
      {
        id: 'kr-eng-2-1',
        title: 'Remediate all 22 high and critical security findings',
        owner: 'Sam Chen',
        target: 22,
        current: 9,
        unit: 'findings',
        dueDate: '2026-06-30',
        status: 'at-risk',
        progress: 41,
        lastUpdated: '2026-05-01',
      },
      {
        id: 'kr-eng-2-2',
        title: 'Complete 100% of SOC 2 control documentation',
        owner: 'Priya Nair',
        target: 100,
        current: 65,
        unit: '%',
        dueDate: '2026-06-30',
        status: 'on-track',
        progress: 65,
        lastUpdated: '2026-05-01',
      },
      {
        id: 'kr-eng-2-3',
        title: 'Pass SOC 2 Type II audit with zero major findings',
        owner: 'Alex Rivera',
        target: 1,
        current: 0,
        unit: 'audit',
        dueDate: '2026-06-30',
        status: 'not-started',
        progress: 0,
        lastUpdated: '2026-05-01',
      },
    ],
  },

  {
    id: 'obj-sales-2',
    title: 'EMEA Market Entry',
    description: 'Open the EMEA market with a dedicated sales motion and first enterprise logos',
    owner: 'Maya Patel',
    teamId: 'sales',
    quarter: 'Q2',
    quarters: ['Q2'],
    cadence: 'quarterly',
    year: 2026,
    startDate: '2026-04-01',
    endDate: '2026-06-30',
    status: 'behind',
    progress: 14,
    tags: ['emea', 'expansion', 'new-markets'],
    keyResults: [
      {
        id: 'kr-sales-2-1',
        title: 'Sign 5 EMEA enterprise contracts by end of Q2',
        owner: 'Maya Patel',
        target: 5,
        current: 1,
        unit: 'contracts',
        dueDate: '2026-06-30',
        status: 'behind',
        progress: 20,
        lastUpdated: '2026-05-01',
      },
      {
        id: 'kr-sales-2-2',
        title: 'Build EMEA sales team to 4 account executives',
        owner: 'Jordan Blake',
        target: 4,
        current: 1,
        unit: 'AEs',
        dueDate: '2026-06-30',
        status: 'behind',
        progress: 25,
        lastUpdated: '2026-05-01',
      },
      {
        id: 'kr-sales-2-3',
        title: 'Achieve £300k pipeline from EMEA outbound motion',
        owner: 'Maya Patel',
        target: 300,
        current: 40,
        unit: '£k',
        dueDate: '2026-06-30',
        status: 'behind',
        progress: 13,
        lastUpdated: '2026-05-01',
      },
    ],
  },

  {
    id: 'obj-mktg-2',
    title: 'Brand & Community',
    description: 'Establish Nexus as a thought leader and build an engaged developer community in Q2',
    owner: 'Remi Okafor',
    teamId: 'marketing',
    quarter: 'Q2',
    quarters: ['Q2'],
    cadence: 'quarterly',
    year: 2026,
    startDate: '2026-04-01',
    endDate: '2026-06-30',
    status: 'on-track',
    progress: 61,
    tags: ['brand', 'community', 'developer'],
    keyResults: [
      {
        id: 'kr-mktg-2-1',
        title: 'Grow developer community to 2,000 active members',
        owner: 'Remi Okafor',
        target: 2000,
        current: 1240,
        unit: 'members',
        dueDate: '2026-06-30',
        status: 'on-track',
        progress: 62,
        lastUpdated: '2026-05-01',
      },
      {
        id: 'kr-mktg-2-2',
        title: 'Host 2 virtual events with 300+ combined attendees',
        owner: 'Yuki Tanaka',
        target: 300,
        current: 170,
        unit: 'attendees',
        dueDate: '2026-06-30',
        status: 'on-track',
        progress: 57,
        lastUpdated: '2026-05-01',
      },
      {
        id: 'kr-mktg-2-3',
        title: 'Place Nexus in 3 industry analyst reports',
        owner: 'Yuki Tanaka',
        target: 3,
        current: 2,
        unit: 'reports',
        dueDate: '2026-06-30',
        status: 'on-track',
        progress: 67,
        lastUpdated: '2026-05-01',
      },
    ],
  },

  // ── Q3 2026 (upcoming / not started) ──────────────────────────────────────

  {
    id: 'obj-prod-2',
    title: 'Enterprise Feature Suite',
    description: 'Deliver the Q3 enterprise feature roadmap to close key competitive gaps',
    owner: 'Daniel Park',
    teamId: 'product',
    quarter: 'Q3',
    quarters: ['Q3'],
    cadence: 'quarterly',
    year: 2026,
    startDate: '2026-07-01',
    endDate: '2026-09-30',
    status: 'not-started',
    progress: 0,
    tags: ['product', 'enterprise', 'roadmap'],
    keyResults: [
      {
        id: 'kr-prod-2-1',
        title: 'Ship SSO and SCIM provisioning for enterprise accounts',
        owner: 'Daniel Park',
        target: 1,
        current: 0,
        unit: 'feature',
        dueDate: '2026-09-30',
        status: 'not-started',
        progress: 0,
        lastUpdated: '2026-05-01',
      },
      {
        id: 'kr-prod-2-2',
        title: 'Ship advanced analytics dashboard with custom report builder',
        owner: 'Chloe Dubois',
        target: 1,
        current: 0,
        unit: 'feature',
        dueDate: '2026-09-30',
        status: 'not-started',
        progress: 0,
        lastUpdated: '2026-05-01',
      },
      {
        id: 'kr-prod-2-3',
        title: 'Achieve feature adoption rate of 30% within 30 days of launch',
        owner: 'Chloe Dubois',
        target: 30,
        current: 0,
        unit: '%',
        dueDate: '2026-09-30',
        status: 'not-started',
        progress: 0,
        lastUpdated: '2026-05-01',
      },
    ],
  },
];

// All quarterly views show the same objectives (filtered by quarter in the UI)
export const allObjectives: Record<string, Objective[]> = {
  Q1: defaultObjectives,
  Q2: defaultObjectives,
  Q3: defaultObjectives,
  Q4: defaultObjectives,
};

// ─── Team definitions ──────────────────────────────────────────────────────

export const teamDefs: TeamDef[] = [
  { id: 'engineering',      name: 'Engineering',      lead: 'Alex Rivera',   color: '#3b82f6', memberCount: 28, description: 'Build and maintain a world-class, reliable platform' },
  { id: 'product',          name: 'Product',          lead: 'Chloe Dubois',  color: '#8b5cf6', memberCount: 12, description: 'Define and ship products that win in the enterprise market' },
  { id: 'sales',            name: 'Sales',            lead: 'Jordan Blake',  color: '#10b981', memberCount: 20, description: 'Acquire new logos and expand revenue in existing accounts' },
  { id: 'marketing',        name: 'Marketing',        lead: 'Yuki Tanaka',   color: '#f59e0b', memberCount: 10, description: 'Drive awareness, demand generation and brand positioning' },
  { id: 'customer-success', name: 'Customer Success', lead: 'Fatima Al-Sayed', color: '#06b6d4', memberCount: 15, description: 'Deliver exceptional customer outcomes and retention' },
  { id: 'people',           name: 'People & Ops',     lead: 'Ingrid Larsson', color: '#ec4899', memberCount: 8,  description: 'Attract, develop and retain top talent across the business' },
];

export const buildCompanyOKR = (
  quarter: 'Q1' | 'Q2' | 'Q3' | 'Q4',
  year: number,
  teamsOverride?: TeamDef[],
  objectivesOverride?: Objective[],
) => {
  const objectives = objectivesOverride ?? allObjectives[quarter] ?? [];
  const defs = teamsOverride ?? teamDefs;

  const teams: Team[] = defs.map(def => {
    const teamObjs = objectives.filter(o => o.teamId === def.id);
    const progress = teamObjs.length
      ? Math.round(teamObjs.reduce((a, o) => a + o.progress, 0) / teamObjs.length)
      : 0;
    return { ...def, objectives: teamObjs, progress };
  }).filter(t => t.objectives.length > 0);

  const individuals: Individual[] = teams.map(t => ({
    id: `ind-${t.id}`,
    name: t.lead,
    role: `Lead, ${t.name}`,
    teamId: t.id,
    teamName: t.name,
    progress: t.progress,
    objectives: t.objectives,
  }));

  const overallProgress = objectives.length
    ? Math.round(objectives.reduce((a, o) => a + o.progress, 0) / objectives.length)
    : 0;

  return { quarter, year, objectives, teams, individuals, overallProgress };
};

export const historicalProgress = [
  { month: 'Jan', progress: 12, target: 15 },
  { month: 'Feb', progress: 24, target: 25 },
  { month: 'Mar', progress: 38, target: 35 },
  { month: 'Apr', progress: 48, target: 45 },
  { month: 'May', progress: 55, target: 55 },
  { month: 'Jun', progress: null, target: 65 },
  { month: 'Jul', progress: null, target: 72 },
  { month: 'Aug', progress: null, target: 80 },
  { month: 'Sep', progress: null, target: 85 },
  { month: 'Dec', progress: null, target: 100 },
];
