import { Objective, Team, Individual } from './types';
import { TeamDef } from './calendarSettings';

// ─── Form3 FY27 Annual OKRs ───────────────────────────────────────────────
// Source: OKR Performance – April slide
// FY27 = April 2026 – March 2027 (UK fiscal year)
// Progress data as of April 2026 (Q1 FY27)

export const form3AnnualObjectives: Objective[] = [
  {
    id: 'fy27-obj-1',
    title: 'Profitability',
    description: 'Deliver FY27 profitability with disciplined execution and financial control',
    owner: 'CFO',
    teamId: 'profitability',
    quarter: 'Q1',
    quarters: ['Q1', 'Q2', 'Q3', 'Q4'],
    cadence: 'yearly',
    year: 2026,
    startDate: '2026-04-01',
    endDate: '2027-03-31',
    status: 'behind',
    progress: 10,
    tags: ['profitability', 'financial-control'],
    keyResults: [
      {
        id: 'fy27-kr-1-1',
        title: 'Achieve FY27 March ARR > FY27 March recurring cost',
        owner: 'CFO',
        target: -14.4,
        current: -16.2,
        unit: '£m net',
        dueDate: '2027-03-31',
        status: 'behind',
        progress: 10,
        lastUpdated: '2026-04-30',
      },
    ],
  },
  {
    id: 'fy27-obj-2',
    title: 'Revenue',
    description: 'Accelerate revenue by increasing customer value & acquiring high value clients',
    owner: 'CRO',
    teamId: 'revenue',
    quarter: 'Q1',
    quarters: ['Q1', 'Q2', 'Q3', 'Q4'],
    cadence: 'yearly',
    year: 2026,
    startDate: '2026-04-01',
    endDate: '2027-03-31',
    status: 'at-risk',
    progress: 6,
    tags: ['revenue', 'growth', 'arr'],
    keyResults: [
      {
        id: 'fy27-kr-2-1',
        title: 'Increase Annual Recurring Revenue from £29.9m to £46m',
        owner: 'CRO',
        target: 46,
        current: 31.6,
        unit: '£m',
        dueDate: '2027-03-31',
        status: 'at-risk',
        progress: 11,
        lastUpdated: '2026-04-30',
      },
      {
        id: 'fy27-kr-2-2',
        title: 'Increase US Annual Recurring Revenue from £0.2m to £2m',
        owner: 'VP Sales USA',
        target: 2,
        current: 0.3,
        unit: '£m',
        dueDate: '2027-03-31',
        status: 'at-risk',
        progress: 6,
        lastUpdated: '2026-04-30',
      },
      {
        id: 'fy27-kr-2-3',
        title: 'Increase Strategic Annual Recurring Revenue from £0 to £8m',
        owner: 'VP Partnerships',
        target: 8,
        current: 0,
        unit: '£m',
        dueDate: '2027-03-31',
        status: 'not-started',
        progress: 0,
        lastUpdated: '2026-04-30',
      },
    ],
  },
  {
    id: 'fy27-obj-3',
    title: 'Operational Efficiency',
    description: 'Reallocate investment to high-impact, high growth initiatives',
    owner: 'COO',
    teamId: 'ops-efficiency',
    quarter: 'Q1',
    quarters: ['Q1', 'Q2', 'Q3', 'Q4'],
    cadence: 'yearly',
    year: 2026,
    startDate: '2026-04-01',
    endDate: '2027-03-31',
    status: 'on-track',
    progress: 64,
    tags: ['operational-efficiency', 'cost', 'investment'],
    keyResults: [
      {
        id: 'fy27-kr-3-1',
        title: 'Improve revenue to platform cloud cost ratio from 5.5 to 10.2',
        owner: 'COO',
        target: 10.2,
        current: 5.55,
        unit: 'ratio',
        dueDate: '2027-03-31',
        status: 'on-track',
        progress: 54,
        lastUpdated: '2026-04-30',
      },
      {
        id: 'fy27-kr-3-2',
        title: 'Achieve 100% of reduction targets in manual interventions across support, onboarding & audit',
        owner: 'COO',
        target: 100,
        current: 100,
        unit: '%',
        dueDate: '2027-03-31',
        status: 'on-track',
        progress: 100,
        lastUpdated: '2026-04-30',
      },
      {
        id: 'fy27-kr-3-3',
        title: 'Reduce the number of support requests per customer',
        owner: 'Head of Operations',
        target: 100,
        current: 100,
        unit: '%',
        dueDate: '2027-03-31',
        status: 'on-track',
        progress: 100,
        lastUpdated: '2026-04-30',
      },
      {
        id: 'fy27-kr-3-4',
        title: 'Increase UI self-served resolution rate',
        owner: 'Head of Product',
        target: 100,
        current: 0,
        unit: '%',
        dueDate: '2027-03-31',
        status: 'not-started',
        progress: 0,
        lastUpdated: '2026-04-30',
      },
    ],
  },
  {
    id: 'fy27-obj-4',
    title: 'Customer',
    description: 'Build a high-performing customer engine that wins, onboards and delivers brilliant service',
    owner: 'CCO',
    teamId: 'customer',
    quarter: 'Q1',
    quarters: ['Q1', 'Q2', 'Q3', 'Q4'],
    cadence: 'yearly',
    year: 2026,
    startDate: '2026-04-01',
    endDate: '2027-03-31',
    status: 'on-track',
    progress: 100,  // avg(100, 99) ≈ 100
    tags: ['customer', 'cpi', 'service'],
    keyResults: [
      {
        id: 'fy27-kr-4-1',
        title: 'Maintain Customer Performance Index (CPI) of ≥80%',
        owner: 'CCO',
        target: 80,
        current: 80,
        unit: '%',
        dueDate: '2027-03-31',
        status: 'on-track',
        progress: 100,
        lastUpdated: '2026-04-30',
      },
      {
        id: 'fy27-kr-4-2',
        title: 'Maintain CPI satisfaction score ≥7.8 (out of 10)',
        owner: 'CCO',
        target: 8.0,
        current: 7.9,
        unit: 'score',
        dueDate: '2027-03-31',
        status: 'on-track',
        progress: 99,
        lastUpdated: '2026-04-30',
      },
    ],
  },
  {
    id: 'fy27-obj-5',
    title: 'Our People',
    description: 'Build a consistently high-performing organisation for talent, performance, and engagement',
    owner: 'CPO',
    teamId: 'people',
    quarter: 'Q1',
    quarters: ['Q1', 'Q2', 'Q3', 'Q4'],
    cadence: 'yearly',
    year: 2026,
    startDate: '2026-04-01',
    endDate: '2027-03-31',
    status: 'on-track',
    progress: 39,
    tags: ['people', 'engagement', 'talent'],
    keyResults: [
      {
        id: 'fy27-kr-5-1',
        title: 'Achieve Engagement Score >8',
        owner: 'CPO',
        target: 8,
        current: 7.9,
        unit: 'score',
        dueDate: '2027-03-31',
        status: 'on-track',
        progress: 99,
        lastUpdated: '2026-04-30',
      },
      {
        id: 'fy27-kr-5-2',
        title: 'Achieve 80% progress of individual performance objectives annually',
        owner: 'CPO',
        target: 80,
        current: 11,
        unit: '%',
        dueDate: '2027-03-31',
        status: 'on-track',
        progress: 14,
        lastUpdated: '2026-04-30',
      },
      {
        id: 'fy27-kr-5-3',
        title: 'Achieve 80% progress of individual development goals annually',
        owner: 'CPO',
        target: 80,
        current: 2,
        unit: '%',
        dueDate: '2027-03-31',
        status: 'at-risk',
        progress: 3,
        lastUpdated: '2026-04-30',
      },
    ],
  },
  {
    id: 'fy27-obj-6',
    title: 'Quality',
    description: 'Drive a culture of operational excellence and compliance',
    owner: 'CTO',
    teamId: 'quality',
    quarter: 'Q1',
    quarters: ['Q1', 'Q2', 'Q3', 'Q4'],
    cadence: 'yearly',
    year: 2026,
    startDate: '2026-04-01',
    endDate: '2027-03-31',
    status: 'on-track',
    progress: 50,
    tags: ['quality', 'compliance', 'reliability'],
    keyResults: [
      {
        id: 'fy27-kr-6-1',
        title: 'Maintain Information Security Performance Index ≥95%',
        owner: 'CISO',
        target: 95,
        current: 96,
        unit: '%',
        dueDate: '2027-03-31',
        status: 'on-track',
        progress: 100,
        lastUpdated: '2026-04-30',
      },
      {
        id: 'fy27-kr-6-2',
        title: 'Maintain Engineering Reliability Score ≥90%',
        owner: 'CTO',
        target: 90,
        current: 100,
        unit: '%',
        dueDate: '2027-03-31',
        status: 'on-track',
        progress: 100,
        lastUpdated: '2026-04-30',
      },
      {
        id: 'fy27-kr-6-3',
        title: 'Increase Ecovadis Score to 65',
        owner: 'Head of Sustainability',
        target: 65,
        current: 0,
        unit: 'score',
        dueDate: '2027-03-31',
        status: 'not-started',
        progress: 0,
        lastUpdated: '2026-04-30',
      },
      {
        id: 'fy27-kr-6-4',
        title: 'Achieve more than 80% of CTP/OpRes targets',
        owner: 'CTO',
        target: 80,
        current: 0,
        unit: '%',
        dueDate: '2027-03-31',
        status: 'not-started',
        progress: 0,
        lastUpdated: '2026-04-30',
      },
    ],
  },
];

// All quarterly views show the same annual objectives
export const allObjectives: Record<string, Objective[]> = {
  Q1: form3AnnualObjectives,
  Q2: form3AnnualObjectives,
  Q3: form3AnnualObjectives,
  Q4: form3AnnualObjectives,
};

// ─── Team definitions matching FY27 OKR pillars ──────────────────────────

export const teamDefs: TeamDef[] = [
  { id: 'profitability',  name: 'Profitability',          lead: 'CFO',  color: '#ef4444', memberCount: 8,  description: 'Deliver FY27 profitability with disciplined execution and financial control' },
  { id: 'revenue',        name: 'Revenue',                lead: 'CRO',  color: '#f59e0b', memberCount: 25, description: 'Accelerate revenue by increasing customer value & acquiring high value clients' },
  { id: 'ops-efficiency', name: 'Operational Efficiency', lead: 'COO',  color: '#10b981', memberCount: 20, description: 'Reallocate investment to high-impact, high growth initiatives' },
  { id: 'customer',       name: 'Customer',               lead: 'CCO',  color: '#06b6d4', memberCount: 15, description: 'Build a high-performing customer engine that wins, onboards and delivers brilliant service' },
  { id: 'people',         name: 'Our People',             lead: 'CPO',  color: '#8b5cf6', memberCount: 10, description: 'Build a consistently high-performing organisation for talent, performance, and engagement' },
  { id: 'quality',        name: 'Quality',                lead: 'CTO',  color: '#6366f1', memberCount: 30, description: 'Drive a culture of operational excellence and compliance' },
];

export const buildCompanyOKR = (
  quarter: 'Q1' | 'Q2' | 'Q3' | 'Q4',
  year: number,
  teamsOverride?: TeamDef[],
  objectivesOverride?: Objective[],
) => {
  const objectives = objectivesOverride ?? allObjectives[quarter] ?? [];
  const defs = teamsOverride ?? teamDefs;

  const teams: Team[] = defs.map(def => {
    const teamObjs = objectives.filter(o => o.teamId === def.id);
    const progress = teamObjs.length
      ? Math.round(teamObjs.reduce((a, o) => a + o.progress, 0) / teamObjs.length)
      : 0;
    return { ...def, objectives: teamObjs, progress };
  }).filter(t => t.objectives.length > 0);

  const individuals: Individual[] = teams.map(t => ({
    id: `ind-${t.id}`,
    name: t.lead,
    role: `Lead, ${t.name}`,
    teamId: t.id,
    teamName: t.name,
    progress: t.progress,
    objectives: t.objectives,
  }));

  const overallProgress = objectives.length
    ? Math.round(objectives.reduce((a, o) => a + o.progress, 0) / objectives.length)
    : 0;

  return { quarter, year, objectives, teams, individuals, overallProgress };
};

// Historical trend — FY27 April actuals + projected
export const historicalProgress = [
  { month: 'Apr', progress: 45, target: 40 },
  { month: 'May', progress: null, target: 50 },
  { month: 'Jun', progress: null, target: 60 },
  { month: 'Jul', progress: null, target: 65 },
  { month: 'Aug', progress: null, target: 70 },
  { month: 'Mar', progress: null, target: 100 },
];
