import { CompanyOKR, Objective, Team, Individual } from './types';

const q2Objectives: Objective[] = [
  {
    id: 'obj-1',
    title: 'Achieve 99.99% platform uptime across all payment rails',
    description: 'Ensure Form3 infrastructure delivers enterprise-grade reliability',
    owner: 'Sarah Mitchell',
    teamId: 'platform',
    quarter: 'Q2',
    year: 2026,
    status: 'on-track',
    progress: 78,
    tags: ['reliability', 'platform'],
    keyResults: [
      {
        id: 'kr-1-1',
        title: 'Reduce P1 incidents to fewer than 3 per quarter',
        owner: 'James Chen',
        target: 3,
        current: 1,
        unit: 'incidents',
        dueDate: '2026-06-30',
        status: 'on-track',
        progress: 85,
        lastUpdated: '2026-05-14',
      },
      {
        id: 'kr-1-2',
        title: 'Achieve 99.99% SLA across all payment schemes',
        owner: 'Sarah Mitchell',
        target: 99.99,
        current: 99.97,
        unit: '%',
        dueDate: '2026-06-30',
        status: 'at-risk',
        progress: 65,
        lastUpdated: '2026-05-15',
      },
      {
        id: 'kr-1-3',
        title: 'Complete chaos engineering test suite coverage',
        owner: 'DevOps Team',
        target: 100,
        current: 82,
        unit: '%',
        dueDate: '2026-06-30',
        status: 'on-track',
        progress: 82,
        lastUpdated: '2026-05-13',
      },
    ],
  },
  {
    id: 'obj-2',
    title: 'Expand into 3 new European payment schemes',
    description: 'Drive geographic expansion across SEPA Instant, BLIK, and Bankgirot',
    owner: 'Marcus Webb',
    teamId: 'product',
    quarter: 'Q2',
    year: 2026,
    status: 'on-track',
    progress: 62,
    tags: ['expansion', 'product'],
    keyResults: [
      {
        id: 'kr-2-1',
        title: 'Launch SEPA Instant for 5 pilot clients',
        owner: 'Product Team',
        target: 5,
        current: 4,
        unit: 'clients',
        dueDate: '2026-05-31',
        status: 'on-track',
        progress: 80,
        lastUpdated: '2026-05-15',
      },
      {
        id: 'kr-2-2',
        title: 'Complete BLIK regulatory approval',
        owner: 'Marcus Webb',
        target: 1,
        current: 0,
        unit: 'approval',
        dueDate: '2026-06-30',
        status: 'at-risk',
        progress: 40,
        lastUpdated: '2026-05-10',
      },
      {
        id: 'kr-2-3',
        title: 'Onboard 2 Bankgirot integration partners',
        owner: 'Partnerships Team',
        target: 2,
        current: 1,
        unit: 'partners',
        dueDate: '2026-06-30',
        status: 'on-track',
        progress: 50,
        lastUpdated: '2026-05-12',
      },
    ],
  },
  {
    id: 'obj-3',
    title: 'Grow ARR by 35% through enterprise deals',
    description: 'Accelerate revenue through Tier-1 bank partnerships and enterprise fintech',
    owner: 'Priya Sharma',
    teamId: 'commercial',
    quarter: 'Q2',
    year: 2026,
    status: 'on-track',
    progress: 71,
    tags: ['revenue', 'commercial'],
    keyResults: [
      {
        id: 'kr-3-1',
        title: 'Close 4 Tier-1 enterprise deals',
        owner: 'Priya Sharma',
        target: 4,
        current: 3,
        unit: 'deals',
        dueDate: '2026-06-30',
        status: 'on-track',
        progress: 75,
        lastUpdated: '2026-05-15',
      },
      {
        id: 'kr-3-2',
        title: 'Achieve £12M in new ACV from Q2 pipeline',
        owner: 'Sales Team',
        target: 12000000,
        current: 8400000,
        unit: '£',
        dueDate: '2026-06-30',
        status: 'on-track',
        progress: 70,
        lastUpdated: '2026-05-14',
      },
      {
        id: 'kr-3-3',
        title: 'Reduce sales cycle to 45 days for mid-market',
        owner: 'Sales Ops',
        target: 45,
        current: 52,
        unit: 'days',
        dueDate: '2026-06-30',
        status: 'at-risk',
        progress: 62,
        lastUpdated: '2026-05-13',
      },
    ],
  },
  {
    id: 'obj-4',
    title: 'Deliver world-class developer experience',
    description: 'Make Form3 APIs the easiest payment APIs to integrate globally',
    owner: 'Alex Torres',
    teamId: 'engineering',
    quarter: 'Q2',
    year: 2026,
    status: 'on-track',
    progress: 84,
    tags: ['developer-experience', 'engineering'],
    keyResults: [
      {
        id: 'kr-4-1',
        title: 'Achieve NPS score of 75+ from developer survey',
        owner: 'Alex Torres',
        target: 75,
        current: 71,
        unit: 'NPS',
        dueDate: '2026-06-30',
        status: 'on-track',
        progress: 80,
        lastUpdated: '2026-05-15',
      },
      {
        id: 'kr-4-2',
        title: 'Reduce time-to-first-API-call to under 15 minutes',
        owner: 'DX Team',
        target: 15,
        current: 18,
        unit: 'minutes',
        dueDate: '2026-06-30',
        status: 'at-risk',
        progress: 70,
        lastUpdated: '2026-05-12',
      },
      {
        id: 'kr-4-3',
        title: 'Publish 20 SDK quickstart guides',
        owner: 'Docs Team',
        target: 20,
        current: 18,
        unit: 'guides',
        dueDate: '2026-06-30',
        status: 'on-track',
        progress: 90,
        lastUpdated: '2026-05-15',
      },
    ],
  },
  {
    id: 'obj-5',
    title: 'Build industry-leading compliance & fraud prevention',
    description: 'Achieve zero tolerance for payment fraud and full regulatory compliance',
    owner: 'Nina Okonkwo',
    teamId: 'risk',
    quarter: 'Q2',
    year: 2026,
    status: 'behind',
    progress: 48,
    tags: ['compliance', 'fraud', 'risk'],
    keyResults: [
      {
        id: 'kr-5-1',
        title: 'Reduce fraud rate to below 0.001%',
        owner: 'Risk Team',
        target: 0.001,
        current: 0.0018,
        unit: '%',
        dueDate: '2026-06-30',
        status: 'behind',
        progress: 44,
        lastUpdated: '2026-05-14',
      },
      {
        id: 'kr-5-2',
        title: 'Complete ISO 27001 recertification',
        owner: 'Nina Okonkwo',
        target: 1,
        current: 0,
        unit: 'cert',
        dueDate: '2026-06-30',
        status: 'at-risk',
        progress: 60,
        lastUpdated: '2026-05-13',
      },
      {
        id: 'kr-5-3',
        title: 'Deploy real-time ML fraud detection v2',
        owner: 'ML Team',
        target: 1,
        current: 0,
        unit: 'deployment',
        dueDate: '2026-06-30',
        status: 'behind',
        progress: 35,
        lastUpdated: '2026-05-10',
      },
    ],
  },
];

export const teams: Team[] = [
  {
    id: 'platform',
    name: 'Platform & Infrastructure',
    description: 'Core payment infrastructure and reliability',
    lead: 'Sarah Mitchell',
    memberCount: 18,
    color: '#6366f1',
    objectives: q2Objectives.filter(o => o.teamId === 'platform'),
    progress: 78,
  },
  {
    id: 'product',
    name: 'Product',
    description: 'Payment scheme expansion and product strategy',
    lead: 'Marcus Webb',
    memberCount: 12,
    color: '#06b6d4',
    objectives: q2Objectives.filter(o => o.teamId === 'product'),
    progress: 62,
  },
  {
    id: 'commercial',
    name: 'Commercial',
    description: 'Sales, partnerships, and revenue growth',
    lead: 'Priya Sharma',
    memberCount: 22,
    color: '#10b981',
    objectives: q2Objectives.filter(o => o.teamId === 'commercial'),
    progress: 71,
  },
  {
    id: 'engineering',
    name: 'Engineering',
    description: 'API development and developer experience',
    lead: 'Alex Torres',
    memberCount: 35,
    color: '#f59e0b',
    objectives: q2Objectives.filter(o => o.teamId === 'engineering'),
    progress: 84,
  },
  {
    id: 'risk',
    name: 'Risk & Compliance',
    description: 'Fraud prevention and regulatory compliance',
    lead: 'Nina Okonkwo',
    memberCount: 9,
    color: '#ef4444',
    objectives: q2Objectives.filter(o => o.teamId === 'risk'),
    progress: 48,
  },
];

export const individuals: Individual[] = [
  { id: 'ind-1', name: 'Sarah Mitchell', role: 'VP Platform', teamId: 'platform', teamName: 'Platform & Infrastructure', progress: 78, objectives: q2Objectives.filter(o => o.teamId === 'platform') },
  { id: 'ind-2', name: 'James Chen', role: 'SRE Lead', teamId: 'platform', teamName: 'Platform & Infrastructure', progress: 85, objectives: q2Objectives.filter(o => o.teamId === 'platform') },
  { id: 'ind-3', name: 'Marcus Webb', role: 'VP Product', teamId: 'product', teamName: 'Product', progress: 62, objectives: q2Objectives.filter(o => o.teamId === 'product') },
  { id: 'ind-4', name: 'Priya Sharma', role: 'Chief Revenue Officer', teamId: 'commercial', teamName: 'Commercial', progress: 71, objectives: q2Objectives.filter(o => o.teamId === 'commercial') },
  { id: 'ind-5', name: 'Alex Torres', role: 'VP Engineering', teamId: 'engineering', teamName: 'Engineering', progress: 84, objectives: q2Objectives.filter(o => o.teamId === 'engineering') },
  { id: 'ind-6', name: 'Nina Okonkwo', role: 'Chief Risk Officer', teamId: 'risk', teamName: 'Risk & Compliance', progress: 48, objectives: q2Objectives.filter(o => o.teamId === 'risk') },
];

export const companyOKR: CompanyOKR = {
  quarter: 'Q2',
  year: 2026,
  objectives: q2Objectives,
  teams,
  individuals,
  overallProgress: Math.round(q2Objectives.reduce((acc, o) => acc + o.progress, 0) / q2Objectives.length),
};

export const historicalProgress = [
  { month: 'Jan', progress: 15, target: 25 },
  { month: 'Feb', progress: 28, target: 35 },
  { month: 'Mar', progress: 44, target: 50 },
  { month: 'Apr', progress: 58, target: 60 },
  { month: 'May', progress: 69, target: 70 },
  { month: 'Jun', progress: null, target: 100 },
];

export const teamProgressData = teams.map(t => ({
  name: t.name.split(' ')[0],
  fullName: t.name,
  progress: t.progress,
  color: t.color,
}));
